### ISSUE TITLE
Pollution in global scope

### ISSUE THREAD

**Issue by jrummell-chromium** [shaka-project/eme_logger#44]
With EME Logger enabled, on an internal site, I get the following error and the page fails to load properly. Without EME Logger enabled the page loads properly.
```
alerts.js:formatted:1 Uncaught SyntaxError: Identifier 'options' has already been declared (at alerts.js:formatted:1:1)
```
eme-trace-config.js does define `const options = ...`, so I assume that alerts.js does the same. The page should probably be changed to use unique names that are unlikely to collide with other pages, or wrap the variables inside a function.

(I also noticed that there are some global functions like `byteToHexString`. I wonder if they should be renamed (or placed inside a class)?)

**Comment by joeyparrish** [comment]
Perhaps instead, the scripts that are injected into the page should have a scope wrapper:

```js
(() => {
  const whateverIWantToCallIt = 'This will not leak';
})();
```

**Comment by joeyparrish** [comment]
See #45 for an example of a public site that breaks because of this

**Comment by matthuisman** [comment]
Fyi. This has been issue for quite a few years. I only just thought of disabling extensions to try to fix :)

**Comment by joeyparrish** [comment]
@matthuisman, thanks for letting us know.  We will work on an update to fix it.
